# Generated by Django 3.1.6 on 2021-02-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gg_manufacturer', models.CharField(max_length=200, verbose_name='GG Manufacturer')),
                ('gg_model', models.CharField(max_length=200, verbose_name='GG Model')),
                ('gg_power', models.CharField(max_length=200, verbose_name='GG power')),
                ('gg_compression', models.CharField(max_length=200, verbose_name='GG compression')),
                ('gg_rpm_lp', models.CharField(max_length=200, verbose_name='GG rmp at low power turbine')),
                ('gg_rpm_hp', models.CharField(max_length=200, verbose_name='GG rmp at high power turbine')),
                ('gg_efficiency', models.CharField(max_length=200, verbose_name='GG efficiency')),
                ('gg_mass', models.CharField(max_length=200, verbose_name='GG mass')),
                ('gg_synt_oil_type', models.CharField(max_length=200, verbose_name='GG type of synthetic oil')),
                ('gg_synt_oil_tank', models.CharField(max_length=200, verbose_name='GG volume of oil tank')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название станции')),
                ('gtu_number', models.CharField(max_length=2, verbose_name='Количество GTU')),
                ('gtu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.gtu')),
            ],
        ),
        migrations.CreateModel(
            name='Shutdowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_type', models.CharField(max_length=10, verbose_name='Shutdown type')),
                ('gtu', models.CharField(max_length=10, verbose_name='GTU down')),
                ('datetime', models.DateTimeField(verbose_name='Shutdown time')),
                ('act_number', models.CharField(max_length=3, verbose_name='Act number')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.station')),
            ],
        ),
    ]
