# Generated by Django 3.1.6 on 2021-02-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shutdowns',
            new_name='Shutdown',
        ),
        migrations.AddField(
            model_name='gtu',
            name='pt_manufacturer',
            field=models.CharField(max_length=200, null=True, verbose_name='GG Manufacturer'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_manufacturer',
            field=models.CharField(max_length=200, verbose_name='Gasgenerator Manufacturer'),
        ),
    ]
