# Generated by Django 3.1.6 on 2021-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_auto_20210217_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Краткое описание причны'),
        ),
    ]
