# Generated by Django 3.1.6 on 2021-02-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_shutdown_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='act_number',
            field=models.CharField(blank=True, max_length=3, verbose_name='Act number'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Shutdown time'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='gtu',
            field=models.CharField(blank=True, max_length=10, verbose_name='GTU down'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stops.station'),
        ),
        migrations.CreateModel(
            name='W_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4)),
                ('gtu', models.CharField(blank=True, max_length=10, verbose_name='Unit')),
                ('w_hours', models.CharField(blank=True, max_length=5, verbose_name='Working hours')),
                ('year_hours', models.CharField(blank=True, max_length=6, verbose_name='Total year hours')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stops.station')),
            ],
        ),
    ]
