# Generated by Django 3.1.6 on 2021-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_auto_20210220_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, upload_to='files/sd_acts<django.db.models.fields.DateTimeField>'),
        ),
    ]
