# Generated by Django 3.1.6 on 2021-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0005_shutdown_sd_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
