# Generated by Django 3.1.6 on 2021-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0007_auto_20210223_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, upload_to='files/333/'),
        ),
    ]
