# Generated by Django 3.1.6 on 2021-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0008_auto_20210223_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, null=True, upload_to='files/333/'),
        ),
    ]
