# Generated by Django 3.1.6 on 2021-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0009_auto_20210223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
