# Generated by Django 3.1.6 on 2021-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0010_auto_20210223_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
