# Generated by Django 3.1.6 on 2021-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0011_auto_20210224_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='sd_type',
            field=models.CharField(choices=[('Auto shutdown', 'Auto shutdown'), ('Forced Normal Stop', 'Forced Normal Stop')], max_length=50, verbose_name='Shutdown type'),
        ),
    ]
