# Generated by Django 3.1.6 on 2021-02-25 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0013_shutdown_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='detailed_desc',
            field=models.TextField(blank=True, verbose_name='Подробное описание причны'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='act_number',
            field=models.CharField(max_length=3, verbose_name='Act number'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Shutdown time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='desc',
            field=models.TextField(verbose_name='Краткое описание причны'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='gtu',
            field=models.CharField(max_length=10, verbose_name='GTU down'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='sd_act',
            field=models.FileField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.station'),
        ),
    ]
