# Generated by Django 3.1.6 on 2021-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0014_auto_20210225_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtu',
            name='gg_compression',
            field=models.CharField(max_length=200, verbose_name='Степень сжатия'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_efficiency',
            field=models.CharField(max_length=200, verbose_name='КПД газогенератора'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_manufacturer',
            field=models.CharField(max_length=200, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_mass',
            field=models.CharField(max_length=200, verbose_name='Масса газогенератора'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_model',
            field=models.CharField(max_length=200, verbose_name='Модель газогенератора'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_power',
            field=models.CharField(max_length=200, verbose_name='Мощность газогенератора'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_rpm_hp',
            field=models.CharField(max_length=200, verbose_name='Скорость вращения ТВД'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_rpm_lp',
            field=models.CharField(max_length=200, verbose_name='Скорость вращения ТНД'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_synt_oil_tank',
            field=models.CharField(max_length=200, verbose_name='Объем бака синтетического масла'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='gg_synt_oil_type',
            field=models.CharField(max_length=200, verbose_name='Тип синтетического масла'),
        ),
        migrations.AlterField(
            model_name='gtu',
            name='pt_manufacturer',
            field=models.CharField(max_length=200, null=True, verbose_name='Производитель Силовой Турбины'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='act_number',
            field=models.CharField(max_length=3, verbose_name='Акт расследования'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время останова'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='desc',
            field=models.TextField(verbose_name='Краткое описание останова'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='detailed_desc',
            field=models.TextField(blank=True, verbose_name='Подробное описание останова'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='gtu',
            field=models.CharField(max_length=10, verbose_name='ГПА №'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='sd_type',
            field=models.CharField(choices=[('Auto shutdown', 'Auto shutdown'), ('Forced Normal Stop', 'Forced Normal Stop')], max_length=50, verbose_name='Тип останова'),
        ),
        migrations.AlterField(
            model_name='station',
            name='gtu_number',
            field=models.CharField(max_length=2, verbose_name='Количество ГПА'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название компрессорной станции'),
        ),
        migrations.AlterField(
            model_name='w_hours',
            name='gtu',
            field=models.CharField(blank=True, max_length=10, verbose_name='ГПА'),
        ),
        migrations.AlterField(
            model_name='w_hours',
            name='w_hours',
            field=models.CharField(blank=True, max_length=5, verbose_name='Наработка в часах'),
        ),
        migrations.AlterField(
            model_name='w_hours',
            name='year_hours',
            field=models.CharField(blank=True, max_length=6, verbose_name='Количество часов в году'),
        ),
    ]
