# Generated by Django 3.1.6 on 2021-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0015_auto_20210225_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='desc',
            field=models.TextField(verbose_name='Причина останова'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='detailed_desc',
            field=models.TextField(blank=True, verbose_name='Подробное описание останова и проведенных мероприятий'),
        ),
        migrations.AlterField(
            model_name='shutdown',
            name='sd_type',
            field=models.CharField(choices=[('АВТО', 'АВТО'), ('ВНО', 'ВНО')], max_length=50, verbose_name='Тип останова'),
        ),
    ]
